SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ( 
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
ON F.FLAVOR  = J.FLAVOR 
ORDER BY (F.TOTAL_ORDER + J.JULY_TOTAL_ORDER) DESC
LIMIT 3